### ISSUE TITLE
ImportError: cannot import name 'SAMPLERS' from partially initialized module 'ssod.datasets.builder' (most likely due to a circular import) (/home/wqz/objdet/softteacher/ssod/datasets/builder.py)

### ISSUE THREAD

**Issue by wqzustc** [microsoft/SoftTeacher#37]

**Comment by MendelXu** [comment]
Could you give more details like the command you run?

**Comment by wqzustc** [comment]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        _delete_=True,
        type="SemiDataset",
        sup=dict(
            type="CocoDataset",
            ann_file=None,
            img_prefix=None,
            pipeline=train_pipeline,
        ),
        unsup=dict(
            type="CocoDataset",
            ann_file=None,
            img_prefix=None,
            pipeline=unsup_pipeline,
            filter_empty_gt=False,
        ),
    ),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline),
    sampler=dict(
        train=dict(
            type="**SemiBalanceSampler**",
            sample_ratio=[1, 4],
            by_prob=True,
            # at_least_one=True,
            epoch_length=7330,
        )
    ),
)
I found that "ssod/datasets/builder.py" not have "SemiBalanceSampler" in SAMPLERS,than I add
from .samplers import DistributedGroupSemiBalanceSampler
SAMPLERS.register_module(module=DistributedGroupSemiBalanceSampler)
in "ssod/datasets/builder.py",than I run train.py,and got this issue

**Comment by MendelXu** [comment]
No. You didn't need to add this line. The `SemiBalanceSampler` is imported in `datasets/samplers/__init__.py`

**Comment by wqzustc** [comment]
Thanks for your response!
but if not have this line. The following error occurs:
KeyError: 'DistributedSemiBalanceSampler is not in the sampler registry'

**Comment by MendelXu** [comment]
Could you post the command you run here?

**Comment by wqzustc** [comment]
Thank you! You are right if I change to distributed it got normal!

**Comment by tahira1996** [comment]
Hi,
I am getting this error

    return build_from_cfg(cfg, SAMPLERS, default_args)
  File "/home/shehzadi/anaconda3/envs/soft1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SemiBalanceSampler is not in the sampler registry'

I am running this file:
python tools/train.py configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_180k.py --gpus 1 --cfg-options fold=1 percent=1

**Comment by MendelXu** [comment]
Don't use it in non-distributed mode. Run the model  as the tutorial said, `bash tools/dist_train.sh {CONFIG_FILE} {GPU_NUM}`

**Comment by liangch123** [comment]
(mmdet) root@autodl-container-dc0d119a52-91304b51:~/SoftTeacher# bash tools/dist_train.sh configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py 2
/root/miniconda3/envs/mmdet/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/root/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/root/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 18, in <module>
    from ssod.apis import get_root_logger, set_random_seed, train_detector
  File "/root/SoftTeacher/ssod/apis/__init__.py", line 1, in <module>
    from .train import get_root_logger, set_random_seed, train_detector
  File "/root/SoftTeacher/ssod/apis/train.py", line 19, in <module>
    from mmdet.datasets import build_dataset, replace_ImageToTensor
  File "/root/mmdetection/mmdet/datasets/__init__.py", line 2, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/root/mmdetection/mmdet/datasets/builder.py", line 15, in <module>
    from .samplers import (ClassAwareSampler, DistributedGroupSampler,
  File "/root/mmdetection/mmdet/datasets/samplers/__init__.py", line 6, in <module>
    from .semi_sampler import DistributedGroupSemiBalanceSampler
  File "/root/mmdetection/mmdet/datasets/samplers/semi_sampler.py", line 8, in <module>
    from ..builder import SAMPLERS
ImportError: cannot import name 'SAMPLERS' from partially initialized module 'mmdet.datasets.builder' (most likely due to a circular import) (/root/mmdetection/mmdet/datasets/builder.py)

**Comment by liangch123** [comment]
>I recompiled it under the soft_teacher file and it was ready to run
