### ISSUE TITLE
Data ratio at the end of the training 

### ISSUE THREAD

**Issue by JasonChen75** [microsoft/SoftTeacher#49]
![image](https://user-images.githubusercontent.com/13853032/136880206-f0557ac8-28f7-4ca7-9249-78063cfec1e8.png)

Hello

I read your paper and found out you have reduced the data sampling ratio to zero (no labeled images at the end of the training?) for the last 20k iterations. 

1. Is there any reason why you did this? 
2. How much does it contribute to the performance of the Fully Labeled Data setting? What is the performance using the constant data ratio?
3. Where is this implemented in the code? I cannot find it. 

Thank you.

**Comment by MendelXu** [comment]
1. We found that the distribution of the output is a little shifted from the true distribution of model trained with ground truth, and we guest it might be caused by the pseudo data. Therefore we try to reduce the unsupervised data gradually at the end. It is somewhat similar to finetuning with true data. 
2. In this repo, we only provide the result trained with the constant data ratio as we find that such a strategy can only reduce the training time but will not contribute to the final performance. For example, if we have a model trained with 360k iterations, and we add such a strategy at the end, then its performance will be comparable to the same model trained with longer iterations. However, the upper bound of the method will not be changed by the strategy.
3. We didn't add it in the repo as it is implemented in a hacky way which will make the code harder to read.
