### ISSUE TITLE
Question about augmentation

### ISSUE THREAD

**Issue by oracl4** [microsoft/SoftTeacher#98]
Hi, thanks for your code implementation. I want to ask about something about the augmentation process. I want to add new augmentation on the framework.

![image](https://user-images.githubusercontent.com/30832572/140765334-5e7eb2a7-33bc-4420-8438-f5a4050fadfe.png)

When I check the implementation and your paper I found that in the paper you define every probability for every augmentation, that means that there are a probability of several augmentation implemented together right ? But when I follow your code there is a OneOf function that select only single augmentation to be implemented, so what is the meaning of the probability on your table ?

![image](https://user-images.githubusercontent.com/30832572/140765645-3d2fcaeb-e5e4-44bd-9d59-f5dc844fd102.png)

Am I not understanding something here ? or something wrong with my understanding on the augmentation process ?

**Comment by MendelXu** [comment]
Yes, your understanding is right. The reason is pretty simple. When we prepared experiments for our paper, we used most of the augmentations implemented in the `mmdetection` framework, and thus no operation like `OneOf`. So we use probabilistic method instead of `OneOf` implemented in `STAC`. And when we planned to release the code, to make it aligned with `STAC`, we implemented some related augmentations and thus remove the probability.

**Comment by oracl4** [comment]
Does the change to follow the STAC augmentation is possible to change the performance of the model ? So if I want to follow the default augmentations I just need to change back into the probabilistic method right ?

Thank you for your answer and implementation!

**Comment by MendelXu** [comment]
If you compare the performance in the paper and the repo, you will find some performance is slightly different.  Yes
